bundle:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  vendor: "Oleg Nenashev"
  title: "Jenkins WAR - Artifact Manager S3 Demo"
  description: "Demo build, which includes S3 Artifact Manager Demo"
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    git: https://github.com/jglick/jenkins.git
    commit: 2090468d82e49345519a2457f1d1e7426f01540b
plugins:
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      git: https://github.com/jglick/workflow-api-plugin.git
      commit: 70472c422619213842f17ec130ed75fa7bcc4a59
  - groupId: "io.jenkins.plugins"
    artifactId: "artifact-manager-s3"
    source:
      git: https://github.com/jenkinsci/artifact-manager-s3-plugin.git
      branch: master
  # Maven HPI Plugin improperly resolves dependency trees, needs upper bounds check
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: 1.10

